DB_URI = "postgresql://neondb_owner:npg_Pp7ctA5jZnQs@ep-delicate-poetry-acxqnji9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[credenciales]
Axel = "Fernando4263"
Bruno = "Pari00"
Usuario = "Prueba1234"